services:
  mysql:
    container_name: virtual_drivers_gpt_mysql
    image: mysql:8
    ports:
      - '3300:3306'
    environment:
      TZ: 'Asia/Seoul'
      MYSQL_DATABASE: virtual_drivers
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./infra/mysql/data:/var/lib/mysql
    networks:
      - virtual-drivers-chatbot
networks:
  virtual-drivers-chatbot:
    name: virtual-drivers-chatbot
    driver: bridge
